title:        Portal
url:          http://my-brothers-keeper-statistical-indicators.apievangelist.com

version:      1.1.1
author:
  name:       'Kin Lane'
  email:      'info@apievangelist.com'
markdown:     rdiscount
permalink:    pretty
pygments:     true

permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

paginate: 50
paginate_path: "/news/page:num"

production_url : http://my-brothers-keeper-statistical-indicators.apievangelist.com


BASE_PATH : http://my-brothers-keeper-statistical-indicators.apievangelist.com


categories_path : /categories.html
tags_path : /tags.html

org: Kin-Lane
repo: my-brothers-keeper-statistical-indicators
resource: my-brothers-keeper-statistical-indicators
